import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './styles/globals.css';
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hekate",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-gray-100 text-gray-900">
      <Navbar/>
      {children}
      <Footer />
      </body>
      
    </html>
  );
}
